title: "Aryan Kini"
date: 2020-06-04
---
title: Aryan Kini's Website
author: Aryan Kini
email: aryankini@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This website is about what I like to do

# social links
twitter_username: DonaldTrump # DO NOT include the @ character, or else the build will fail!
github_username:  Akini123456 # DO NOT include the @ character, or else the build will fail!
theme: minima

show_excerpts: true # set to false to remove excerpts on the homepage
